name: Distribute and deploy docs

on:
  push:
    branches: [ main ]
  # Release are automated while events triggered by the GITHUB_TOKEN do not create a new workflow run.
  # See: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
  # Hence, not relying on the commented lines below.
  release:
    types: [ published ]

jobs:
  build-and-distribute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/python-poetry-env

      - name: Distribute to pypi
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --build --no-interaction

      - name: Deploy docs
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: poetry run mkdocs gh-deploy --force
